/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as LivestockRouteImport } from './routes/livestock'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CropsCropIdRouteImport } from './routes/crops.$cropId'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const LivestockRoute = LivestockRouteImport.update({
  id: '/livestock',
  path: '/livestock',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsCropIdRoute = CropsCropIdRouteImport.update({
  id: '/$cropId',
  path: '/$cropId',
  getParentRoute: () => CropsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crops': typeof CropsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/livestock': typeof LivestockRoute
  '/weather': typeof WeatherRoute
  '/crops/$cropId': typeof CropsCropIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crops': typeof CropsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/livestock': typeof LivestockRoute
  '/weather': typeof WeatherRoute
  '/crops/$cropId': typeof CropsCropIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crops': typeof CropsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/livestock': typeof LivestockRoute
  '/weather': typeof WeatherRoute
  '/crops/$cropId': typeof CropsCropIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/crops'
    | '/dashboard'
    | '/knowledge'
    | '/livestock'
    | '/weather'
    | '/crops/$cropId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/crops'
    | '/dashboard'
    | '/knowledge'
    | '/livestock'
    | '/weather'
    | '/crops/$cropId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/crops'
    | '/dashboard'
    | '/knowledge'
    | '/livestock'
    | '/weather'
    | '/crops/$cropId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CropsRoute: typeof CropsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LivestockRoute: typeof LivestockRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livestock': {
      id: '/livestock'
      path: '/livestock'
      fullPath: '/livestock'
      preLoaderRoute: typeof LivestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/$cropId': {
      id: '/crops/$cropId'
      path: '/$cropId'
      fullPath: '/crops/$cropId'
      preLoaderRoute: typeof CropsCropIdRouteImport
      parentRoute: typeof CropsRoute
    }
  }
}

interface CropsRouteChildren {
  CropsCropIdRoute: typeof CropsCropIdRoute
}

const CropsRouteChildren: CropsRouteChildren = {
  CropsCropIdRoute: CropsCropIdRoute,
}

const CropsRouteWithChildren = CropsRoute._addFileChildren(CropsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CropsRoute: CropsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  KnowledgeRoute: KnowledgeRoute,
  LivestockRoute: LivestockRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
